name = "Kembang"
license = "MIT"
licenselink = "https://github.com/aznkh/kembang/blob/main/LICENSE"
description = "Minimalist Blogging Theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/aznkh/kembang"

# If you have a running demo of the theme.
demosite = "https://kembang-theme.netlify.app/"

tags = ["blog", "minimalist"]
features = ["bootstrap", "local font"]


# If the theme has a single author
[author]
    name = "Aziz"
    homepage = "https://github.com/aznkh"

