baseURL = "https://example.com"
languageCode = "en"
title = "Kembang"
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 6
disableHugoGeneratorInject = true

[params]
custom_css = [ "/css/main.css", "/css/normalize.css", "/css/bootstrap.css"]
description = 'Kembang Theme'
author = "Aziz NK"
homeDownload = "Want this theme ? Download [here](https://www.github.com/aznkh/kembang). Thanks"

   
[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
